# Generated by Django 5.0.6 on 2024-05-20 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(max_length=255)),
                ('customerAddress', models.TextField()),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('approved', models.BooleanField(default=False)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=255)),
                ('productId', models.CharField(max_length=50, unique=True)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productDes', models.TextField(blank=True, null=True)),
                ('productRating', models.FloatField()),
                ('productDisCount', models.CharField(blank=True, max_length=10, null=True)),
                ('productHave', models.BooleanField()),
                ('productBrand', models.CharField(max_length=255)),
                ('productImage', models.ImageField(upload_to='product_images/')),
                ('productDlb', models.FileField(upload_to='product_files/')),
                ('productCategory', models.CharField(max_length=255)),
                ('productNote', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='api.OrderItem', to='api.product'),
        ),
    ]
